baseurl = "https://dpritchett.net"
canonifyurls = true
contentdir = "content"
languageCode = "en-us"
layoutsdir = "layouts"
publishdir = "public"
theme = "hugo-kiera"
title = "Daniel Pritchett"
verbose = true
verboseLog = true
googleAnalytics = "UA-39163683-1"
enableRobotsTXT = true

[params]
        name = "Daniel Pritchett"
        description = "Notes on building cloud software and systems for humans by Daniel Pritchett."
        tagline = "Notes on building cloud software and systems for humans by Daniel Pritchett."
        bio = "Consulting engineer: Kubernetes, Serverless, DevOps. Publishing a book on chatbots. Ask me about hearing aids, Ruby programming, and cloud infrastructure!"
        twitter = "dpritchett"
        enableRSS = true

[author]
    name = "Daniel Pritchett"
    github   = "dpritchett"
    twitter  = "dpritchett"
    linkedin  = "danielpritchett"
